spring.application.name=PaymentApp
server.port=8443
stripe.public-key="KEY"

server.ssl.key-store=classpath:keystore.p12
server.ssl.key-store-password=PASSWORD
server.ssl.key-store-type=PKCS12
server.ssl.key-alias=SEP