<project>
    <modelVersion>4.0.0</modelVersion>

    <groupId>com.ftn.SEP.payment</groupId>
    <artifactId>payment-parent</artifactId>
    <version>1.0.0</version>
    <packaging>pom</packaging>

    <modules>
        <module>common</module>
        <module>PaymentApp</module>
        <module>ShopApp</module>
    </modules>

    <properties>
        <java.version>17</java.version>
        <spring.boot.version>4.0.1</spring.boot.version>
        <lombok.version>1.18.38</lombok.version>
    </properties>

    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-dependencies</artifactId>
                <version>${spring.boot.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
        </dependencies>
    </dependencyManagement>
</project>
